# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.

service: apollo-lambda
# app and org for use with dashboard.serverless.com
app: apollo-lambda
org: bhushanbharat

provider:
  name: aws
  runtime: nodejs12.x
  # you can overwrite defaults here
  stage: dev
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["MenuTable", "Arn"] }
  environment:
    MENU: ${self:custom.menutable}

plugins:
  - serverless-webpack
  - serverless-plugin-include-dependencies
  - serverless-dynamodb-local
  - serverless-offline #needs to be last in the list so dynamoDB can be started offline for testing**

# Custom Settings
custom:
  menutable: "espresso-bar-menu-${self:provider.stage}"
  serverless-offline:
    port: 4000
  #webpackIncludeModules: true
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
    packager: yarn
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      inMemory: true
      convertEmptyValues: true

# GraphQL endpoint Config

functions:
  graphql:
    handler: server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true

# DynamoDB Config

resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.menutable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
